### PR TITLE
added rounding before converting float32 to uint8

### PR DESCRIPTION
**Pull request by jonasrauber**
Following the discussion on Gitter (see following quote from me) and some offline discussions we have decided to add proper rounding before converting floats to integers. While attacks could do this themselves, we haven't see many attacks actually doing it (acutally our own baselines also don't do it) and the current way of rounding is just not what one would expect.

> **@jonasrauber:**
Hi @csy530216, thank you for your in-depth analysis of this issue. I'll try to help! So far I am not fully convinced yet that we actually have a problem that needs fixing, but let's discuss further. While it would be nice to support small per pixel perturbations (< 1 for pixel values between 0 and 255) we cannot do that because that would give models an easy way to detect most adversarial perturbations (clean images only have integer values). So to avoid leaking information to the model, we are enforcing that all adversarials are in uint8 format as well. In other words: the smallest possible (non-zero) perturbation for each pixel is 1. Note that we do not just convert to uint8 in store_adversarial (i.e. when saving the adversarial and calculating the distance), but also during inference (the model always only gets integer inputs). In that sense we determine the size of the actual perturbation seen by the model and whether we map [i, i+1) to i or [i - 0.5, i + 0.5) should in principle not matter: Actually your attack could just add 0.5 to everything it passes to the model and you would get the desired behavior. Nevertheless, I see that, from a practical point of view, it's nicer if we do that (i.e. rounding to the nearest integer == adding 0.5 before rounding down). Not sure if it's worth changing the interface for that, however (in theory someone might have already built upon the current assumptions). What do you think?

This pull-request contains the necessary changes (actually it's just adding one line). This will affect both `predict` and `store_adversarial`.

@spMohanty Can you confirm that, once we release this as a new version, this will automatically be part of all new submissions and the evaluation coming up these days (if released before then)
@wielandbrendel Can you decide when to do go live with this update (I think I would risk doing it now, before the evaluation.)
@bveliqi Can you review and merge this PR and release a new version as soon as @wielandbrendel gives his okay.

### CODE REVIEW

**Comment by spMohanty** [comment]
@jonasrauber : Once merged and released, this will be included in all the subsequent submissions.

For the offline evaluations it is a bit tricky, if not impossible, to have this included in all the previous submissions.

The reason being, many participants have already deleted their source/tag from their repositories; which we do have the docker images for the same. Now either we rebuild all the docker images from the available source/tags associated with a submission, **and exclude all submissions whose corresponding source has been deleted**.

Or we take the docker image, and do a `pip install -U adversarial-vision-challenge`, but we will have to repeat the step with pip and pip3, as some participants might be using python2 and some others python3. If they have a custom and non standard python reference in their image (and in run.sh) then the changes wont be reflected either. But this one would be a very ugly solution imho.

cc. @MasterScrat

**Review by bveliqi — APPROVED** [review]

**Comment by jonasrauber** [comment]
@spMohanty thanks for the fast response; it's okay if old submissions have the old package version, and all future submissions have the new one… but could I ask you to rebuild the baseline attacks so that they will use the new package (@bveliqi will let you know once he released the new version; should be soon)

@spMohanty just out of curiosity: why would anyone delete the source / tags for an active submission? how do they even do this, force pushing over the repository?

**Comment by spMohanty** [comment]
@jonasrauber : Yes we will rebuild the baselines as soon as the new release is ready.

And yeah, anyone can simply delete a particular tag like they would any other git tag; or simply delete the whole repository. While there are some ways we considered which would disable any delete operations; but its more tricky from the point of view of code ownership and licenses, as the individual participants own the content (code) they create, and have every right to delete it as and when they please. Infact, they can even request the corresponding derivatives (docker images built from their code), to be deleted.

For now, we really do not have a good solution for this, other than including it in the rules, that only submissions for which the corresponding source code is still available on gitlab.crowdai.org are eligible for the prizes.

**Comment by bveliqi** [comment]
Release `1.0.5` is out.

**Comment by jonasrauber** [comment]
Thanks @bveliqi!

@spMohanty Yes, I get that, but then the question is: if people delete there code, doesn't it basically mean they withdraw their submission and we can ignore it?

Anyway, let's ignore this for now. Update is released, so baselines can be updated and we can finally have the evaluation round! Thanks :)

**Comment by spMohanty** [comment]
@jonasrauber : Just started the rebuilding of all the baselines. It usually takes about 20-30minutes.

And yeah, regarding the deleted source; its mostly a policy decision; I would also choose to see it that way that if you delete your source code for a submission, then this submission is considered as withdrawn; and we exclude those submissions. But we will have to communicate this very clearly before this can be actually enforced.

**Pull request merged**
